version: '3.3'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432


  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
